internal: fix unused variable build failures w/mips
On mips builds, we see:

internal.c:132:36: error: unused variable 'par_programmer_internal' [-Werror,-Wunused-const-variable]
static const struct par_programmer par_programmer_internal = {

internal.c: In function 'internal_init':
internal.c:206:6: error: variable 'probe_target_bus_later' set but not used [-Werror=unused-but-set-variable]
  int probe_target_bus_later = 0;

BUG=b:27084589
TEST=precq passes & `emerge-mipseb-o32-generic flashrom` works now
BRANCH=None

Change-Id: I86e5c37dc71fc107de37ffd76852ccf695c988a2
Reviewed-on: https://chromium-review.googlesource.com/327390
Commit-Ready: Mike Frysinger <vapier@chromium.org>
Tested-by: Mike Frysinger <vapier@chromium.org>
Reviewed-by: David Hendricks <dhendrix@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/341130
Tested-by: Chia-Hsiu Chang <chia-hsiu.chang@quantatw.com>
Commit-Queue: Chia-Hsiu Chang <chia-hsiu.chang@quantatw.com>