Add CONFIG_FDTMAP to read flashmap from FDT
Chrome OS uses a more powerful flashmap format with support for compression,
description of each section and so on. Flashrom doesn't really need this
information - it just need a section name and start/size. But by making
flashrom understand the Chrome OS format natively, we can avoid having
two copies of the flashmap in the image, with the confusion of which is
correct.

Add a new config for this option and implement it using libfdt and some
simple code from U-Boot.

BUG=chromium-os:38794
BRANCH=none
TEST=Just build it:
sudo emerge flashrom; emerge-daisy flashrom; emerge-link flashrom

Then run the unit tests:

 * Running flashrom unit tests
Testing fdtmap
dtc -O dtb -o test.dtb test.dts
sudo ../flashrom -p dummy:emulate=SST25VF032B,image=image.bin -w part.bin -i RO_ONESTOP
ERROR: ld.so: object 'libsandbox.so' from LD_PRELOAD cannot be preloaded: ignored.
flashrom v0.9.4  :  :  on Linux 3.2.5-gg987 (x86_64), built with libpci 3.1.10, GCC 4.7.x-google 20120720 (prerelease), little endian
Erasing and writing flash chip... Verifying flash... VERIFIED.
SUCCESS
sudo ../flashrom -p dummy:emulate=SST25VF032B,image=image.bin -r part.bin -i RO_ONESTOP
ERROR: ld.so: object 'libsandbox.so' from LD_PRELOAD cannot be preloaded: ignored.
flashrom v0.9.4  :  :  on Linux 3.2.5-gg987 (x86_64), built with libpci 3.1.10, GCC 4.7.x-google 20120720 (prerelease), little endian
Reading flash... SUCCESS
sudo rm -f part.bin
ERROR: ld.so: object 'libsandbox.so' from LD_PRELOAD cannot be preloaded: ignored.
.dtc -O dtb -o test.dtb test.dts
sudo ../flashrom -p dummy:emulate=SST25VF032B,image=image.bin -w part.bin -i RO_ONESTOP
ERROR: ld.so: object 'libsandbox.so' from LD_PRELOAD cannot be preloaded: ignored.
flashrom v0.9.4  :  :  on Linux 3.2.5-gg987 (x86_64), built with libpci 3.1.10, GCC 4.7.x-google 20120720 (prerelease), little endian
Erasing and writing flash chip... Verifying flash... VERIFIED.
SUCCESS
sudo ../flashrom -p dummy:emulate=SST25VF032B,image=image.bin -r part.bin -i RO_ONESTOP
ERROR: ld.so: object 'libsandbox.so' from LD_PRELOAD cannot be preloaded: ignored.
flashrom v0.9.4  :  :  on Linux 3.2.5-gg987 (x86_64), built with libpci 3.1.10, GCC 4.7.x-google 20120720 (prerelease), little endian
Reading flash... SUCCESS
sudo rm -f part.bin
ERROR: ld.so: object 'libsandbox.so' from LD_PRELOAD cannot be preloaded: ignored.
.dtc -O dtb -o test.dtb test.dts
sudo ../flashrom -p dummy:emulate=SST25VF032B,image=image.bin -w part.bin -i RO_ONESTOP
ERROR: ld.so: object 'libsandbox.so' from LD_PRELOAD cannot be preloaded: ignored.
flashrom v0.9.4  :  :  on Linux 3.2.5-gg987 (x86_64), built with libpci 3.1.10, GCC 4.7.x-google 20120720 (prerelease), little endian
No layout info is available.
FAILED
.dtc -O dtb -o test.dtb test.dts
sudo ../flashrom -p dummy:emulate=SST25VF032B,image=image.bin -w part.bin -i RO_ONESTOP
ERROR: ld.so: object 'libsandbox.so' from LD_PRELOAD cannot be preloaded: ignored.
flashrom v0.9.4  :  :  on Linux 3.2.5-gg987 (x86_64), built with libpci 3.1.10, GCC 4.7.x-google 20120720 (prerelease), little endian
No layout info is available.
FAILED
.dtc -O dtb -o test.dtb test.dts
sudo ../flashrom -p dummy:emulate=SST25VF032B,image=image.bin -w part.bin -i RO_ONESTOP
ERROR: ld.so: object 'libsandbox.so' from LD_PRELOAD cannot be preloaded: ignored.
flashrom v0.9.4  :  :  on Linux 3.2.5-gg987 (x86_64), built with libpci 3.1.10, GCC 4.7.x-google 20120720 (prerelease), little endian
No layout info is available.
FAILED
.dtc -O dtb -o test.dtb test.dts
sudo ../flashrom -p dummy:emulate=SST25VF032B,image=image.bin -w part.bin -i RO_ONESTOP
ERROR: ld.so: object 'libsandbox.so' from LD_PRELOAD cannot be preloaded: ignored.
flashrom v0.9.4  :  :  on Linux 3.2.5-gg987 (x86_64), built with libpci 3.1.10, GCC 4.7.x-google 20120720 (prerelease), little endian
Erasing and writing flash chip... Verifying flash... VERIFIED.
SUCCESS
sudo ../flashrom -p dummy:emulate=SST25VF032B,image=image.bin -r part.bin -i RO_ONESTOP
ERROR: ld.so: object 'libsandbox.so' from LD_PRELOAD cannot be preloaded: ignored.
flashrom v0.9.4  :  :  on Linux 3.2.5-gg987 (x86_64), built with libpci 3.1.10, GCC 4.7.x-google 20120720 (prerelease), little endian
Reading flash... SUCCESS
sudo rm -f part.bin
ERROR: ld.so: object 'libsandbox.so' from LD_PRELOAD cannot be preloaded: ignored.
.
----------------------------------------------------------------------
Ran 6 tests in 14.639s

OK

Change-Id: I52044515f4fb95368d5cc4b44a51543d354f1f46
Signed-off-by: Simon Glass <sjg@chromium.org>
Reviewed-on: https://gerrit.chromium.org/gerrit/43010